language: go
go:
  - 1.5.1
os:
  - linux
before_script:
  - git clone git://github.com/mseshachalam/mseshachalam.github.io-hugo.git mseshachalam.github.io-hugo
  - git clone git://github.com/mseshachalam/mseshachalam.github.io.git mseshachalam.github.io
  - git clone git://github.com/spf13/hyde.git mseshachalam.github.io-hugo/themes/hyde
script:
  - hugo -t hyde
install:
  - go get -v -u github.com/spf13/hugo
