sudo: false
language: go
go:
- 1.5.1
os:
- linux
before_script:
- git clone git://github.com/mseshachalam/mseshachalam.github.io-hugo.git mseshachalam.github.io-hugo
- git clone git://github.com/mseshachalam/mseshachalam.github.io.git mseshachalam.github.io
- git clone git://github.com/mseshachalam/hyde-x.git mseshachalam.github.io-hugo/themes/hyde-x
- ln -s `pwd`/mseshachalam.github.io `pwd`/mseshachalam.github.io-hugo/public
script:
- cd mseshachalam.github.io-hugo
- hugo -t hyde-x
- cd ..
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rev=$(git
  rev-parse --short HEAD)
- cd mseshachalam.github.io
- git config user.email "seshachalam@outlook.com"
- git config user.name "Seshachalam Malisetti"
- git pull origin master
- git remote rm origin
- git remote add origin "https://$GH_TOKEN@github.com/mseshachalam/mseshachalam.github.io.git"
- git add --all
- git commit -m "rebuild pages at ${rev}"
- git push origin master
- curl https://google.com/webmasters/sitemaps/ping?sitemap=https://tagitbitch.com/sitemap.xml
- curl https://www.bing.com/ping?sitemap=https://tagitbitch.com/sitemap.xml
- chmod a+x process.bash
- source ./process.bash
- [ -z "$PB_BODY" ] && (curl --header 'Access-Token: $PB_TOKEN' \
       --header 'Content-Type: application/json' \
       --data-binary $PB_BODY \
       --request POST \
       https://api.pushbullet.com/v2/pushes);
install:
- go get -v -u github.com/spf13/hugo
env:
  global:
  - secure: nLrW2dHcLaRp5We9/rYerlUoriDqVqNhMOSyrWoB2uPi/oKr/BjM7FXvESEOBwpAjMtbIywi8IaMbaGYQDUqDDVL7pGyqf8h2RBlcpPD9x4Y/69NMnBGDQHUukEjbqRhZSnunVk5XUTKUWLvLfTd8G9vShb6KXx8T+Sym7YJTb9S+orVzjSJQIArAfrhX6jsP8ZzV1BC70P/6EjUgsnX7m8ldmR7rOHOW2DsP40lvxE4I5PEPwzD+iv5fRbiamKc0C4ExKGVQoaAIMzfUwOp/lLwHpt1qUbVi7SuVPGqiP2iAcxaVL3Vr9oUwNRxzW5p01decbLwZv87co/Kl8SkRMQPMqnbr4mzMWXiLd7pMfTZeFyQNL/oX3BiducAoBeCW9iI6G1BDzlLj7NmlsSv64QtKoy5kgv1GmM70Ogl6Ugvf+i6OlwXMBd+7SME580HwlM/Xat/AUjStmkV9UL172J7aXMEuux6+qbX43MyTOFuQ30mtSn5rJ4xRXeuoSS9xqwnNphOfMiXIRYcp4V7QQd44/BDeV8cN0Szt7JegH3OenhBCNKTFeqlO1FH6rUDNE/AjO793h1sqDOWhN4QDJ/O10xrHeLmSZmBizNCBd2Hyy0NUHQMdQGpOm8z5N5cBuofHWMwby4DCCQUa7nCC2B58GBJhojsr7sGdXm4qEg=
  - secure: jan3bVYXWU0D64f80D66h20t19Wt7Cs8MWNBY4I1dDzTo6TaBxqga0FLojvvol7rNil7+XymXPBjfzyjuROrKc559XzD6JJksDoO2YgGm7EQxzXb/DraWX7ne+nfBF9ib328KnT6vGr3KQz1EAwj1cTxv6e9WtFdMLe7xirM0oZZvNGKVgESaAL8UtAXkdDFmh2crJiA3jNV0bIMMRfvZoGWwotv2F4MI0tEKzJH84Pc/YsDoANoIND8Z+brWLxJma4S3GAp2+Vcd6/wpZSD3KwAhD+5U061ZLgjGhXFGMw6clq/Ph5vnd3sYBuF31czzwnDWFvRDMci5u2GDxqGsqloSKyfBG60QvIqgqOR9uVv0xc+aTTJVAHoeNjIxLOG2SUJuJTYxHQIVFJxvs9vHz2RkVsQTWOop2SCjzRBtDyx2IjZJc7HWkImlbILtvtoJDD8yPqjvAf1pAPdczkS9QujH/B4cNr4AXrfEhS0gKnL/PsBfA7RhAdc7IyaZvRM741sjh/UzuvuVgvR+7wrG8zLvNa3O91xKgopt0pl7vIHAl1047XNjWuJlZVumIs52L8x7GNwcAXSOarNWsDn3GJyP4mH+gjRXXepGPrRFb1rQhmKJXFxL9Rn+0oZKdKpuLFD+ir36db6DJY+4GCsTMTaggepmv9QaDQ3FH5Akaw=
