language: go
go:
  - 1.5.1
os:
  - linux
before_script:
  - git clone git://github.com/mseshachalam/mseshachalam.github.io-hugo.git mseshachalam.github.io-hugo
  - mkdir mseshachalam.github.io
  - git clone git://github.com/mseshachalam/mseshachalam.github.io.git mseshachalam.github.io
script:
  - hugo -t hyde
install:
  - go get github.com/spf13/hugo
