baseurl = "https://tagitbitch.com/"
languageCode = "en-us"
title = "Tag it b!"
theme = "hyde"

[params]
  	themeColor = "theme-base-0b"
  	description = "My personal blog."
  	disqusShortname = "tagitbitch"
  	googleAnalytics = "UA-58634272-3"
